M48
; DRILL file {KiCad (6.0.9)} date Wed May 10 12:51:23 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-10T12:51:23+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X3.0Y-3.0
X19.0Y-97.0
X45.0Y-3.0
X45.0Y-97.0
T0
M30
