M48
; DRILL file {KiCad (6.0.9)} date Sun Jul 16 00:03:46 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-16T00:03:46+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X69.23Y-31.41
X69.23Y-37.19
T2
X24.0Y-25.0
X35.2Y-89.49
X63.8Y-89.49
X71.0Y-25.0
T0
M30
